apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: com.hammerspace.csi
  name: restored-block-pv
  labels:
    name: restored-block-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: com.hammerspace.csi
    volumeAttributes:
      blockBackingShareName: k8s-block-storage
      mode: Block
      size: "1073741824"
    volumeHandle: /k8s-block-storage/csi-k8s-pvc-b55c132c-5f1a-11ea-b1fd-42010a800016
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hs-storage-block
  volumeMode: Block
