apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: com.hammerspace.csi
  name: restored-filebacked-pv
  labels:
    name: restored-filebacked-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  csi:
    driver: com.hammerspace.csi
    fsType: ext4
    volumeAttributes:
      fsType: ext4
      mode: Filesystem
      mountBackingShareName: k8s-file-backed
      size: "1073741824"
    volumeHandle: /k8s-file-backed/csi-k8s-pvc-7b6d0529-5fb4-11ea-b1fd-42010a800016
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hs-storage-file-backed
  volumeMode: Filesystem