kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-restored
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: hs-storage-file-backed
  selector:
    matchLabels:
      name: restored-filebacked-pv
