apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: com.hammerspace.csi
  name: restored-nfs-pv-test
  labels:
    name: restored-nfs-pv-test
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  csi:
    driver: com.hammerspace.csi
    fsType: nfs
    volumeAttributes:
      mode: Filesystem
    volumeHandle: /test-restore
  persistentVolumeReclaimPolicy: Retain
  storageClassName: hs-storage
  volumeMode: Filesystem
