---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs-restored
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: hs-storage
  selector:
    matchLabels:
      name: restored-nfs-pv-test
