---
apiVersion: v1
kind: Service
metadata:
  name: test-restore
  labels:
    app: test-restore
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: test-restore
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-restore
  labels:
    app: test-restore
spec:
  serviceName: "test-restore"
  replicas: 3
  selector:
    matchLabels:
      app: test-restore
  template:
    metadata:
      labels:
        app: test-restore
    spec:
      containers:
      - args:
        - sleep
        - "3600"
        image: busybox
        imagePullPolicy: IfNotPresent
        name: test-volume-pod
        resources: {}
        volumeMounts:
          - mountPath: "/test"
            name: nfs-restored
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
        - name: nfs-restored
          persistentVolumeClaim:
            claimName: nfs-restored
